### ISSUE TITLE
Future support for kotlin?

### ISSUE THREAD

**Issue by lilstiffy** [pwgit-create/AppWish#16]
Hi Peter I really like AppWish, my question is if you plan to support Kotlin in the future? :)

**Comment by pwgit-create** [comment]
Thank you for your kind words about AppWish!
I haven't made any plans to add Kotlin support yet, but it's not out of the question to add such a feature to the current app. A special AppWish version for Kotlin can also be produced. I'll contemplate it and if I decide to include it, I'll keep you updated on this issue.
