### ISSUE TITLE
Suggestion for readme changes

### ISSUE THREAD

**Issue by lilstiffy** [pwgit-create/AppWish#17]
Hi Peter I read the readme file of appwish and found this section

Credentials requirements (Needed for API Key)
 1. An account (free or paid) at OpenAI https://platform.openai.com/account/

Maybe you can have it bullet point instead of having them numbered list since it only contains one row in this scenario

**Comment by pwgit-create** [comment]
Hi lilstiffy, 
I appreciate your suggestion and will include it in my to-do list (and fix ASAP).
Have a wonderful day!

Best regards
Peter Westin
